// <auto-generated />
using System;
using ExemploTokenBased.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExemploTokenBased.Data.Migrations
{
    [DbContext(typeof(TokenBasedContext))]
    [Migration("20220908215938_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExemploTokenBased.Model.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasAlternateKey("NomeUsuario");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ff37ac0-75bb-4dc9-9cc8-b5259d01088a"),
                            HashSenha = "123abc",
                            NomeUsuario = "admin",
                            Papel = "Admin",
                            Setor = "Administração"
                        },
                        new
                        {
                            Id = new Guid("7b94e9d7-b3a4-417e-95f8-f26bd261c609"),
                            HashSenha = "123abc",
                            NomeUsuario = "carlos",
                            Papel = "Admin",
                            Setor = "Vendas"
                        });
                });

            modelBuilder.Entity("ExemploTokenBased.Model.ValorMoeda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ValoresMoeda", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("073ce8bb-d9be-4f72-9d1d-e7152d58974d"),
                            Data = new DateTime(2022, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 5.0499999999999998
                        },
                        new
                        {
                            Id = new Guid("901a33b7-9949-4330-832a-aa9bba66db45"),
                            Data = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 4.9500000000000002
                        },
                        new
                        {
                            Id = new Guid("77da11b5-efc9-466a-abdb-edbb7639016f"),
                            Data = new DateTime(2022, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 5.25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
