// <auto-generated />
using System;
using ExemploApiKeys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExemploApiKeys.Data.Migrations
{
    [DbContext(typeof(ApiKeyContext))]
    [Migration("20220906212228_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExemploApiKeys.Model.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ff37ac0-75bb-4dc9-9cc8-b5259d01088a"),
                            ApiKey = "527EA1E66C3C1D9D278B6FC4FEE5919E",
                            Ativo = true,
                            Nome = "Cliente X"
                        },
                        new
                        {
                            Id = new Guid("adc6e73f-0f0a-4acf-97ed-b40af27b108b"),
                            ApiKey = "8A66C40830B388B86C2C89926E80C29F",
                            Ativo = false,
                            Nome = "Cliente Z"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
